using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;

using BBDown.Core.Protobuf;

using Google.Protobuf;

using static BBDown.Core.Entity.Entity;
using static BBDown.Core.Util.HTTPUtil;

namespace BBDown.Core.Util;

public static partial class SubUtil
{
    //https://i0.hdslb.com/bfs/subtitle/subtitle_lan.json
    public static (string, string) GetSubtitleCode(string key)
    {
        //zh-hans => zh-Hans
        if (NonCapsRegex( ).Match(key) is { Success: true } result)
        {
            var v = result.Value;
            key = key.Replace(v, v.ToUpper( ));
        }

        return key switch
        {
            "ai-Zh" => ("chi", "中文（简体, AI识别）"),
            "ai-En" => ("eng", "English(generated by ai)"),
            "zh-CN" => ("chi", "中文（简体）"),
            "zh-HK" => ("chi", "中文（香港繁體）"),
            "zh-Hans" => ("chi", "中文（简体）"),
            "zh-TW" => ("chi", "中文（台灣繁體）"),
            "zh-Hant" => ("chi", "中文（繁體）"),
            "en-US" => ("eng", "English(USA)"),
            "ja" => ("jpn", "日本語"),
            "ko" => ("kor", "한국어"),
            "zh-SG" => ("chi", "中文（新加坡）"),
            "ab" => ("abk", "Аҳәынҭқарра"),
            "aa" => ("aar", "Qafár af"),
            "af" => ("afr", "Afrikaans"),
            "sq" => ("alb", "Gjuha shqipe"),
            "ase" => ("ase", "American Sign Language"),
            "am" => ("amh", "አማርኛ"),
            "arc" => ("arc", "ܐܪܡܝܐ"),
            "hy" => ("arm", "հայերեն"),
            "as" => ("asm", "অসমীয়া"),
            "ay" => ("aym", "Aymar aru"),
            "az" => ("aze", "Azərbaycan"),
            "bn" => ("ben", "বাংলা ভাষার"),
            "ba" => ("bak", "Башҡорттеле"),
            "eu" => ("baq", "Euskara"),
            "be" => ("bel", "беларуская мова biełaruskaja mova"),
            "bh" => ("bih", "Bihar"),
            "bi" => ("bis", "Bislama"),
            "bs" => ("bos", "босански"),
            "br" => ("bre", "Breton"),
            "bg" => ("bul", "български"),
            "yue" => ("chi", "粵語"),
            "yue-HK" => ("chi", "粵語（中國香港）"),
            "ca" => ("cat", "català"),
            "chr" => ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"),
            "cho" => ("cho", "Chahta'"),
            "co" => ("cos", "lingua corsa"),
            "hr" => ("hrv", "Hrvatska"),
            "cs" => ("cze", "čeština"),
            "da" => ("dan", "Dansk"),
            "nl" => ("dut", "Nederlands"),
            "nl-BE" => ("dut", "Nederlands(Belgisch)"),
            "nl-NL" => ("dut", "Nederlands(Nederlands)"),
            "dz" => ("dzo", "རྫོང་ཁ།"),
            "en" => ("eng", "English"),
            "en-CA" => ("eng", "English(Canada)"),
            "en-IE" => ("eng", "English(Ireland)"),
            "en-GB" => ("eng", "English(UK)"),
            "eo" => ("epo", "Esperanto"),
            "et" => ("est", "Eestlane"),
            "fo" => ("fao", "føroyskt"),
            "fj" => ("fij", "Vakaviti"),
            "fil" => ("phi", "Pilipino"),
            "fi" => ("fin", "Suomi"),
            "fr" => ("fre", "Français"),
            "fr-BE" => ("fre", "Français(Belgique)"),
            "fr-CA" => ("fre", "Français(Canada)"),
            "fr-FR" => ("fre", "Français(La France)"),
            "fr-CH" => ("fre", "Français(Suisse)"),
            "ff" => ("ful", "Fulani"),
            "gl" => ("glg", "galego"),
            "ka" => ("geo", "ქართული ენა"),
            "de" => ("ger", "Deutsch"),
            "de-AT" => ("ger", "Deutsch(Österreich)"),
            "de-DE" => ("ger", "Deutsch(Deutschland)"),
            "de-CH" => ("ger", "Deutsch(Schweiz)"),
            "el" => ("gre", "Ελληνικά"),
            "kl" => ("kal", "Kalaallisut"),
            "gn" => ("grn", "avañe'ẽ"),
            "gu" => ("guj", "ગુજરાતી"),
            "hak" => ("hak", "Hak-kâ-fa"),
            "hak-TW" => ("hak", "Hak-kâ-fa"),
            "ha" => ("hau", "هَوُسَ"),
            "iw" => ("heb", "שפה עברית"),
            "hi" => ("hin", "हिन्दी"),
            "hi-Latn" => ("hin", "हिंदी(फोनेटिक)"),
            "hu" => ("hun", "Magyar"),
            "is" => ("ice", "icelandic"),
            "ig" => ("ibo", "Asụsụ Igbo"),
            "id" => ("ind", "Indonesia"),
            "ia" => ("ina", "Interlingua"),
            "iu" => ("iku", "ᐃᓄᒃᑎᑐᑦ"),
            "ik" => ("ipk", "Inupiat"),
            "ga" => ("gle", "Gaeilge na hÉireann"),
            "it" => ("ita", "Italiano"),
            "jv" => ("jav", "ꦧꦱꦗꦮ"),
            "kn" => ("kan", "ಕನ್ನಡ"),
            "ks" => ("kas", "कॉशुर"),
            "kk" => ("kaz", "Қазақ тілі"),
            "km" => ("khm", "ភាសាខ្មែរ"),
            "rw" => ("kin", "Ikinyarwanda"),
            "tlh" => ("tlh", "tlhIngan Hol"),
            "ku" => ("kur", "Kurdî"),
            "ky" => ("kir", "кыргыз тили"),
            "lo" => ("lao", "ພາສາລາວ"),
            "la" => ("lat", "latīna"),
            "lv" => ("lav", "latviešu valoda"),
            "ln" => ("lin", "Lingála"),
            "lt" => ("lit", "lietuvių kalba"),
            "lb" => ("ltz", "Lëtzebuergesch"),
            "mk" => ("mac", "Македонски јазик"),
            "mg" => ("mlg", "maa.laa.gaas"),
            "ms" => ("may", "Melayu"),
            "ml" => ("mal", "മലയാളം"),
            "mt" => ("mlt", "Lingwa Maltija"),
            "mi" => ("mao", "Māori"),
            "mr" => ("mar", "मराठी Marāṭhī"),
            "mas" => ("mas", "Maasai"),
            "nan" => ("nan", "閩南語"),
            "nan-TW" => ("nan", "閩南語(台灣)"),
            "lus" => ("lus", "Mizo ṭawng"),
            "mo" => ("mol", "Limba moldovenească"),
            "mn" => ("mon", "монгол хэл"),
            "my" => ("bur", "မြန်မာဘာသာ"),
            "na" => ("nau", "Dorerin Naoero"),
            "nv" => ("nav", "Diné bizaad"),
            "ne" => ("nep", "नेपाली Nepālī"),
            "no" => ("nor", "norsk språk"),
            "fa" => ("per", "فارسی"),
            "fa-AF" => ("per", "فارسی"),
            "fa-IR" => ("per", "فارسی"),
            "pl" => ("pol", "Polski"),
            "pt" => ("por", "Português"),
            "pt-BR" => ("por", "Português(brasil)"),
            "pt-PT" => ("por", "Português(portugal)"),
            "ro" => ("rum", "Română"),
            "ru" => ("rus", "Русский"),
            "ru-Latn" => ("rus", "Русский(фонетический)"),
            "sr" => ("srp", "Српски"),
            "sr-Cyrl" => ("srp", "Српски(ћирилица)"),
            "sr-Latn" => ("srp", "Српски(латиница)"),
            "sh" => ("scr", "srpskohrvatski"),
            "sk" => ("slo", "slovenský"),
            "es" => ("spa", "Español"),
            "es-419" => ("spa", "Español(Latinoamérica)"),
            "es-MX" => ("spa", "Español(México)"),
            "es-ES" => ("spa", "Español(España)"),
            "es-US" => ("spa", "Español(Estados Unidos)"),
            "sv" => ("swe", "Svenska"),
            "tl" => ("tgl", "Tagalog"),
            "th" => ("tha", "ไทย"),
            "tr" => ("tur", "Türkçe"),
            "uk" => ("ukr", "Українська"),
            "ur" => ("urd", "Urdu"),
            "vi" => ("vie", "Tiếng Việt"),
            //"ie"                => ("", ""),
            //"oc"                => ("",   ""),
            //"or"                => ("",   ""),
            //"om"                => ("",   ""),
            //"ps"                => ("",   ""),
            //"pa"                => ("",   ""),
            //"qu"                => ("",   ""),
            //"rm"                => ("",   ""),
            //"rn"                => ("",   ""),
            //"sm"                => ("",   ""),
            //"sg"                => ("",   ""),
            //"sa"                => ("",   ""),
            //"gd"                => ("",   ""),
            //"sdp"               => ("",   ""),
            //"sn"                => ("",   ""),
            //"scn"               => ("",   ""),
            //"sd"                => ("",   ""),
            //"si"                => ("",   ""),
            //"sl"                => ("",   ""),
            //"so"                => ("",   ""),
            //"st"                => ("",   ""),
            //"su"                => ("",   ""),
            //"sw"                => ("",   ""),
            //"ss"                => ("",   ""),
            //"tg"                => ("",   ""),
            //"ta"                => ("",   ""),
            //"tt"                => ("",   ""),
            //"te"                => ("",   ""),
            //"ti"                => ("",   ""),
            //"to"                => ("",   ""),
            //"ts"                => ("",   ""),
            //"tn"                => ("",   ""),
            //"tk"                => ("",   ""),
            //"tw"                => ("",   ""),
            //"uz"                => ("",   ""),
            //"vo"                => ("",   ""),
            //"cy"                => ("",   ""),
            //"fy"                => ("",   ""),
            //"wo"                => ("",   ""),
            //"xh"                => ("",   ""),
            //"yi"                => ("",   ""),
            //"yo"                => ("",   ""),
            //"zu"                => ("",   ""),
            _ => ("und", "Undetermined")
        };
    }

    #region 字幕接口

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi1Async(string aid, string cid, string epId, int index, AppConfig cfg)
    {
        try
        {
            List<Subtitle> subtitles = [];
            var api = "https://" + (cfg.EpHost == "api.bilibili.com" ? "api.biliintl.com" : cfg.EpHost) + $"/intl/gateway/web/v2/subtitle?episode_id={epId}";
            var json = await GetWebSourceAsync(api, cfg);
            using var infoJson = JsonDocument.Parse(json);
            JsonElement.ArrayEnumerator subs = infoJson.RootElement.GetProperty("data").GetProperty("subtitles").EnumerateArray( );
            foreach (JsonElement sub in subs)
            {
                var lan = sub.GetProperty("lang_key").ToString( );
                var url = sub.GetProperty("url").ToString( );
                subtitles.Add(BuildSubtitle(aid, cid, lan, url, true));
            }

            EnsureValidUrls(subtitles);

            return subtitles;
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetIntlSubtitlesFromApi2Async(string aid, string cid, string epId, int index, AppConfig cfg)
    {
        try
        {
            List<Subtitle> subtitles = [];
            var api = "https://" + (cfg.Host == "api.bilibili.com" ? "api.bilibili.tv" : cfg.Host) +
                         $"/intl/gateway/v2/ogv/view/app/season?ep_id={epId}&platform=android&s_locale=zh_SG" + (cfg.Token != "" ? $"&access_key={cfg.Token}" : "");
            var json = await GetWebSourceAsync(api, cfg);
            using var infoJson = JsonDocument.Parse(json);
            JsonElement.ArrayEnumerator subs = infoJson.RootElement.GetProperty("result").GetProperty("modules")[0].GetProperty("data")
                .GetProperty("episodes")[index - 1].GetProperty("subtitles").EnumerateArray( );
            foreach (JsonElement sub in subs)
            {
                var lan = sub.GetProperty("key").ToString( );
                var url = sub.GetProperty("url").ToString( ).Replace("\\\\/", "/");
                subtitles.Add(BuildSubtitle(aid, cid, lan, url, true));
            }

            EnsureValidUrls(subtitles);

            return subtitles;
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi1Async(string aid, string cid, string epId, int index, AppConfig cfg)
    {
        try
        {
            List<Subtitle> subtitles = [];
            var api = $"https://api.bilibili.com/x/web-interface/view?aid={aid}&cid={cid}";
            var json = await GetWebSourceAsync(api, cfg);
            using var infoJson = JsonDocument.Parse(json);
            JsonElement.ArrayEnumerator subs = infoJson.RootElement.GetProperty("data").GetProperty("subtitle").GetProperty("list").EnumerateArray( );
            foreach (JsonElement sub in subs)
            {
                var lan = sub.GetProperty("lan").ToString( );
                subtitles.Add(BuildSubtitle(aid, cid, lan, sub.GetProperty("subtitle_url").ToString( ), false));
            }

            EnsureValidUrls(subtitles);

            return subtitles;
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi2Async(string aid, string cid, string epId, int index, AppConfig cfg)
    {
        try
        {
            List<Subtitle> subtitles = [];
            var api = $"https://api.bilibili.com/x/player/wbi/v2?cid={cid}&aid={aid}";
            var json = await GetWebSourceAsync(api, cfg);
            using var infoJson = JsonDocument.Parse(json);
            JsonElement.ArrayEnumerator subs = infoJson.RootElement.GetProperty("data").GetProperty("subtitle").GetProperty("subtitles").EnumerateArray( );
            foreach (JsonElement sub in subs)
            {
                var lan = sub.GetProperty("lan").ToString( );
                subtitles.Add(BuildSubtitle(aid, cid, lan, sub.GetProperty("subtitle_url").ToString( ), false));
            }

            EnsureValidUrls(subtitles);

            return subtitles;
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static byte[] GetPayload(long aid, long cid)
    {
        var obj = new DmViewReq
        {
            Pid = aid,
            Oid = cid,
            Type = 1,
            Spmid = "main.ugc-video-detail.0.0",
        };
        return AppHelper.PackMessage(obj.ToByteArray( ));
    }

    private static async Task<List<Subtitle>?> GetSubtitlesFromApi3Async(string aid, string cid, string epId, int index)
    {
        try
        {
            List<Subtitle> subtitles = [];
            //grpc调用接口 protobuf
            var api = "https://app.biliapi.net/bilibili.community.service.dm.v1.DM/DmView";

            var data = GetPayload(Convert.ToInt64(aid), Convert.ToInt64(cid));

            var t = AppHelper.ReadMessage(await GetPostResponseAsync(api, data));
            DmViewReply resp = new MessageParser<DmViewReply>(( ) => new DmViewReply( )).ParseFrom(t);

            if (resp.Subtitle != null && resp.Subtitle.Subtitles != null)
            {
                subtitles.AddRange(resp.Subtitle.Subtitles.Select(item => new Subtitle( )
                {
                    url = item.SubtitleUrl,
                    lan = item.Lan,
                    path = $"{aid}/{aid}.{cid}.{item.Lan}.srt"
                }));
            }
            EnsureValidUrls(subtitles);

            return subtitles;
        }
        catch (Exception)
        {
            return null;
        }
    }

    private static Subtitle BuildSubtitle(string aid, string cid, string lan, string url, bool intl)
    {
        var ext = intl ? (url.Contains(".json") ? ".srt" : ".ass") : ".srt";
        return new Subtitle
        {
            url = url,
            lan = lan,
            path = $"{aid}/{aid}.{cid}.{lan}{ext}"
        };
    }

    private static void EnsureValidUrls(List<Subtitle> subtitles)
    {
        // 有空的URL 不合法
        if (subtitles.Any(s => string.IsNullOrEmpty(s.url)))
            throw new Exception("Bad url");
    }

    #endregion

    public static async Task<List<Subtitle>> GetSubtitlesAsync(string aid, string cid, string epId, int index, bool intl, AppConfig cfg)
    {
        List<Subtitle>? subtitles = [];
        if (intl)
        {
            subtitles = await GetIntlSubtitlesFromApi1Async(aid, cid, epId, index, cfg) ?? await GetIntlSubtitlesFromApi2Async(aid, cid, epId, index, cfg);
        }
        else
        {
            if (cfg.Cookie == "")
            {
                subtitles = await GetSubtitlesFromApi3Async(aid, cid, epId, index); // 未登录只有APP可以拿到字幕了
            }
            else
            {
                subtitles = await GetSubtitlesFromApi2Async(aid, cid, epId, index, cfg)
                            ?? await GetSubtitlesFromApi1Async(aid, cid, epId, index, cfg)
                            ?? await GetSubtitlesFromApi3Async(aid, cid, epId, index);
            }
        }

        if (subtitles == null)
        {
            return []; //返回空列表
        }

        //修正 url 协议
        foreach (Subtitle item in subtitles)
        {
            if (item.url.StartsWith("//")) item.url = "https:" + item.url;
        }

        return subtitles;
    }

    public static async Task SaveSubtitleAsync(string url, string path, AppConfig cfg)
    {
        if (path.EndsWith(".srt"))
            await File.WriteAllTextAsync(path, ConvertSubFromJson(await GetWebSourceAsync(url, cfg)), Encoding.UTF8);
        else
            await File.WriteAllTextAsync(path, await GetWebSourceAsync(url, cfg), Encoding.UTF8);
    }

    private static string ConvertSubFromJson(string jsonString)
    {
        StringBuilder lines = new( );
        var json = JsonDocument.Parse(jsonString);
        var sub = json.RootElement.GetProperty("body").EnumerateArray( ).ToList( );
        for (var i = 0; i < sub.Count; i++)
        {
            JsonElement line = sub[i];
            lines.AppendLine((i + 1).ToString( ));
            if (line.TryGetProperty("from", out JsonElement from))
            {
                lines.AppendLine($"{FormatTime(from.GetDouble( ))} --> {FormatTime(line.GetProperty("to").GetDouble( ))}");
            }
            else
            {
                lines.AppendLine($"{FormatTime(0.0)} --> {FormatTime(line.GetProperty("to").GetDouble( ))}");
            }
            //有的没有内容
            if (line.TryGetProperty("content", out JsonElement content))
                lines.AppendLine(content.ToString( ));
            lines.AppendLine( );
        }

        return lines.ToString( );
    }

    private static string FormatTime(double sec) //64.13
    {
        return TimeSpan.FromSeconds(sec).ToString(@"hh\:mm\:ss\,fff");
    }

    [GeneratedRegex("-[a-z]")]
    private static partial Regex NonCapsRegex( );
}