using System;
using System.Collections.Frozen;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Text;
using System.Text.Json;
using System.Text.RegularExpressions;
using System.Threading.Tasks;

using BBDown.Core.Protobuf;

using Google.Protobuf;

using static BBDown.Core.Entity.Entity;
using static BBDown.Core.Util.HTTPUtil;

namespace BBDown.Core.Util;

public static partial class SubUtil
{
    //https://i0.hdslb.com/bfs/subtitle/subtitle_lan.json
    private static readonly FrozenDictionary<string, (string Code, string Name)> SubtitleCodes =
        new Dictionary<string, (string Code, string Name)>
        {
            ["ai-Zh"] = ("chi", "中文（简体, AI识别）"),
            ["ai-En"] = ("eng", "English(generated by ai)"),
            ["zh-CN"] = ("chi", "中文（简体）"),
            ["zh-HK"] = ("chi", "中文（香港繁體）"),
            ["zh-Hans"] = ("chi", "中文（简体）"),
            ["zh-TW"] = ("chi", "中文（台灣繁體）"),
            ["zh-Hant"] = ("chi", "中文（繁體）"),
            ["en-US"] = ("eng", "English(USA)"),
            ["ja"] = ("jpn", "日本語"),
            ["ko"] = ("kor", "한국어"),
            ["zh-SG"] = ("chi", "中文（新加坡）"),
            ["ab"] = ("abk", "Аҳәынҭқарра"),
            ["aa"] = ("aar", "Qafár af"),
            ["af"] = ("afr", "Afrikaans"),
            ["sq"] = ("alb", "Gjuha shqipe"),
            ["ase"] = ("ase", "American Sign Language"),
            ["am"] = ("amh", "አማርኛ"),
            ["arc"] = ("arc", "ܐܪܡܝܐ"),
            ["hy"] = ("arm", "հայերեն"),
            ["as"] = ("asm", "অসমীয়া"),
            ["ay"] = ("aym", "Aymar aru"),
            ["az"] = ("aze", "Azərbaycan"),
            ["bn"] = ("ben", "বাংলা ভাষার"),
            ["ba"] = ("bak", "Башҡорттеле"),
            ["eu"] = ("baq", "Euskara"),
            ["be"] = ("bel", "беларуская мова biełaruskaja mova"),
            ["bh"] = ("bih", "Bihar"),
            ["bi"] = ("bis", "Bislama"),
            ["bs"] = ("bos", "босански"),
            ["br"] = ("bre", "Breton"),
            ["bg"] = ("bul", "български"),
            ["yue"] = ("chi", "粵語"),
            ["yue-HK"] = ("chi", "粵語（中國香港）"),
            ["ca"] = ("cat", "català"),
            ["chr"] = ("chr", "ᏣᎳᎩ ᎦᏬᏂᎯᏍᏗ"),
            ["cho"] = ("cho", "Chahta'"),
            ["co"] = ("cos", "lingua corsa"),
            ["hr"] = ("hrv", "Hrvatska"),
            ["cs"] = ("cze", "čeština"),
            ["da"] = ("dan", "Dansk"),
            ["nl"] = ("dut", "Nederlands"),
            ["nl-BE"] = ("dut", "Nederlands(Belgisch)"),
            ["nl-NL"] = ("dut", "Nederlands(Nederlands)"),
            ["dz"] = ("dzo", "རྫོང་ཁ།"),
            ["en"] = ("eng", "English"),
            ["en-CA"] = ("eng", "English(Canada)"),
            ["en-IE"] = ("eng", "English(Ireland)"),
            ["en-GB"] = ("eng", "English(UK)"),
            ["eo"] = ("epo", "Esperanto"),
            ["et"] = ("est", "Eestlane"),
            ["fo"] = ("fao", "føroyskt"),
            ["fj"] = ("fij", "Vakaviti"),
            ["fil"] = ("phi", "Pilipino"),
            ["fi"] = ("fin", "Suomi"),
            ["fr"] = ("fre", "Français"),
            ["fr-BE"] = ("fre", "Français(Belgique)"),
            ["fr-CA"] = ("fre", "Français(Canada)"),
            ["fr-FR"] = ("fre", "Français(La France)"),
            ["fr-CH"] = ("fre", "Français(Suisse)"),
            ["ff"] = ("ful", "Fulani"),
            ["gl"] = ("glg", "galego"),
            ["ka"] = ("geo", "ქართული ენა"),
            ["de"] = ("ger", "Deutsch"),
            ["de-AT"] = ("ger", "Deutsch(Österreich)"),
            ["de-DE"] = ("ger", "Deutsch(Deutschland)"),
            ["de-CH"] = ("ger", "Deutsch(Schweiz)"),
            ["el"] = ("gre", "Ελληνικά"),
            ["kl"] = ("kal", "Kalaallisut"),
            ["gn"] = ("grn", "avañe'ẽ"),
            ["gu"] = ("guj", "ગુજરાતી"),
            ["hak"] = ("hak", "Hak-kâ-fa"),
            ["hak-TW"] = ("hak", "Hak-kâ-fa"),
            ["ha"] = ("hau", "هَوُسَ"),
            ["iw"] = ("heb", "שפה עברית"),
            ["hi"] = ("hin", "हिन्दी"),
            ["hi-Latn"] = ("hin", "हिंदी(फोनेटिक)"),
            ["hu"] = ("hun", "Magyar"),
            ["is"] = ("ice", "icelandic"),
            ["ig"] = ("ibo", "Asụsụ Igbo"),
            ["id"] = ("ind", "Indonesia"),
            ["ia"] = ("ina", "Interlingua"),
            ["iu"] = ("iku", "ᐃᓄᒃᑎᑐᑦ"),
            ["ik"] = ("ipk", "Inupiat"),
            ["ga"] = ("gle", "Gaeilge na hÉireann"),
            ["it"] = ("ita", "Italiano"),
            ["jv"] = ("jav", "ꦧꦱꦗꦮ"),
            ["kn"] = ("kan", "ಕನ್ನಡ"),
            ["ks"] = ("kas", "कॉशुर"),
            ["kk"] = ("kaz", "Қазақ тілі"),
            ["km"] = ("khm", "ភាសាខ្មែរ"),
            ["rw"] = ("kin", "Ikinyarwanda"),
            ["tlh"] = ("tlh", "tlhIngan Hol"),
            ["ku"] = ("kur", "Kurdî"),
            ["ky"] = ("kir", "кыргыз тили"),
            ["lo"] = ("lao", "ພາສາລາວ"),
            ["la"] = ("lat", "latīna"),
            ["lv"] = ("lav", "latviešu valoda"),
            ["ln"] = ("lin", "Lingála"),
            ["lt"] = ("lit", "lietuvių kalba"),
            ["lb"] = ("ltz", "Lëtzebuergesch"),
            ["mk"] = ("mac", "Македонски јазик"),
            ["mg"] = ("mlg", "maa.laa.gaas"),
            ["ms"] = ("may", "Melayu"),
            ["ml"] = ("mal", "മലയാളം"),
            ["mt"] = ("mlt", "Lingwa Maltija"),
            ["mi"] = ("mao", "Māori"),
            ["mr"] = ("mar", "मराठी Marāṭhī"),
            ["mas"] = ("mas", "Maasai"),
            ["nan"] = ("nan", "閩南語"),
            ["nan-TW"] = ("nan", "閩南語(台灣)"),
            ["lus"] = ("lus", "Mizo ṭawng"),
            ["mo"] = ("mol", "Limba moldovenească"),
            ["mn"] = ("mon", "монгол хэл"),
            ["my"] = ("bur", "မြန်မာဘာသာ"),
            ["na"] = ("nau", "Dorerin Naoero"),
            ["nv"] = ("nav", "Diné bizaad"),
            ["ne"] = ("nep", "नेपाली Nepālī"),
            ["no"] = ("nor", "norsk språk"),
            ["fa"] = ("per", "فارسی"),
            ["fa-AF"] = ("per", "فارسی"),
            ["fa-IR"] = ("per", "فارسی"),
            ["pl"] = ("pol", "Polski"),
            ["pt"] = ("por", "Português"),
            ["pt-BR"] = ("por", "Português(brasil)"),
            ["pt-PT"] = ("por", "Português(portugal)"),
            ["ro"] = ("rum", "Română"),
            ["ru"] = ("rus", "Русский"),
            ["ru-Latn"] = ("rus", "Русский(фонетический)"),
            ["sr"] = ("srp", "Српски"),
            ["sr-Cyrl"] = ("srp", "Српски(ћирилица)"),
            ["sr-Latn"] = ("srp", "Српски(латиница)"),
            ["sh"] = ("scr", "srpskohrvatski"),
            ["sk"] = ("slo", "slovenský"),
            ["es"] = ("spa", "Español"),
            ["es-419"] = ("spa", "Español(Latinoamérica)"),
            ["es-MX"] = ("spa", "Español(México)"),
            ["es-ES"] = ("spa", "Español(España)"),
            ["es-US"] = ("spa", "Español(Estados Unidos)"),
            ["sv"] = ("swe", "Svenska"),
            ["tl"] = ("tgl", "Tagalog"),
            ["th"] = ("tha", "ไทย"),
            ["tr"] = ("tur", "Türkçe"),
            ["uk"] = ("ukr", "Українська"),
            ["ur"] = ("urd", "Urdu"),
            ["vi"] = ("vie", "Tiếng Việt"),
        }.ToFrozenDictionary( );

    public static (string Code, string Name) GetSubtitleCode(string key)
    {
        //zh-hans => zh-Hans
        if (NonCapsRegex( ).Match(key) is { Success: true } result)
        {
            var v = result.Value;
            key = key.Replace(v, v.ToUpper( ));
        }

        return SubtitleCodes.TryGetValue(key, out var value) ? value : ("und", "Undetermined");
    }

    #region 字幕接口

    // 任一环节抛异常或返回空 URL 都视为该接口不可用，由调用方回退到下一个候选
    private static async Task<List<Subtitle>?> TryFetchAsync(Func<Task<List<Subtitle>>> fetch)
    {
        try
        {
            var subtitles = await fetch( );
            return subtitles.Exists(s => string.IsNullOrEmpty(s.url)) ? null : subtitles;
        }
        catch (Exception)
        {
            return null;
        }
    }

    internal static List<Subtitle> ReadSubtitles(JsonElement array, string lanKey, string urlKey, string pathPrefix, bool intl)
    {
        return array.EnumerateArray( ).Select(sub =>
        {
            var lan = sub.GetProperty(lanKey).ToString( );
            var url = sub.GetProperty(urlKey).ToString( ).Replace("\\\\/", "/");
            // 国际版只有 json 接口给的是可转 srt 的结构，其余是 ass 成品
            var ext = !intl || url.Contains(".json") ? ".srt" : ".ass";
            return new Subtitle { lan = lan, url = url, path = $"{pathPrefix}.{lan}{ext}" };
        }).ToList( );
    }

    #endregion

    public static async Task<List<Subtitle>> GetSubtitlesAsync(string aid, string cid, string epId, int index, bool intl, AppConfig cfg)
    {
        var pathPrefix = $"{aid}/{aid}.{cid}";

        async Task<List<Subtitle>> FromJsonAsync(string api, Func<JsonElement, JsonElement> locate, string lanKey, string urlKey)
        {
            using var json = JsonDocument.Parse(await GetWebSourceAsync(api, cfg));
            return ReadSubtitles(locate(json.RootElement), lanKey, urlKey, pathPrefix, intl);
        }

        async Task<List<Subtitle>> FromAppAsync( )
        {
            const string api = "https://app.biliapi.net/bilibili.community.service.dm.v1.DM/DmView";
            var payload = AppHelper.PackMessage(new DmViewReq
            {
                Pid = Convert.ToInt64(aid),
                Oid = Convert.ToInt64(cid),
                Type = 1,
                Spmid = "main.ugc-video-detail.0.0",
            }.ToByteArray( ));
            var body = AppHelper.ReadMessage(await GetPostResponseAsync(api, payload));
            var reply = new MessageParser<DmViewReply>(( ) => new DmViewReply( )).ParseFrom(body);
            return reply.Subtitle?.Subtitles?
                .Select(s => new Subtitle { lan = s.Lan, url = s.SubtitleUrl, path = $"{pathPrefix}.{s.Lan}.srt" })
                .ToList( ) ?? [];
        }

        var intlWebHost = cfg.EpHost == "api.bilibili.com" ? "api.biliintl.com" : cfg.EpHost;
        var intlAppHost = cfg.Host == "api.bilibili.com" ? "api.bilibili.tv" : cfg.Host;
        var accessKey = cfg.Token.Length != 0 ? $"&access_key={cfg.Token}" : "";

        // 候选接口按优先级排列，第一个成功返回的结果生效
        Func<Task<List<Subtitle>>>[] candidates = intl
            ?
            [
                ( ) => FromJsonAsync($"https://{intlWebHost}/intl/gateway/web/v2/subtitle?episode_id={epId}",
                    root => root.GetProperty("data").GetProperty("subtitles"), "lang_key", "url"),
                ( ) => FromJsonAsync($"https://{intlAppHost}/intl/gateway/v2/ogv/view/app/season?ep_id={epId}&platform=android&s_locale=zh_SG{accessKey}",
                    root => root.GetProperty("result").GetProperty("modules")[0].GetProperty("data").GetProperty("episodes")[index - 1].GetProperty("subtitles"),
                    "key", "url"),
            ]
            : cfg.Cookie.Length == 0
                // 未登录只有 APP 端能拿到字幕
                ? [FromAppAsync]
                :
                [
                    ( ) => FromJsonAsync($"https://api.bilibili.com/x/player/wbi/v2?cid={cid}&aid={aid}",
                        root => root.GetProperty("data").GetProperty("subtitle").GetProperty("subtitles"), "lan", "subtitle_url"),
                    ( ) => FromJsonAsync($"https://api.bilibili.com/x/web-interface/view?aid={aid}&cid={cid}",
                        root => root.GetProperty("data").GetProperty("subtitle").GetProperty("list"), "lan", "subtitle_url"),
                    FromAppAsync,
                ];

        foreach (var candidate in candidates)
        {
            if (await TryFetchAsync(candidate) is not { } subtitles)
            {
                continue;
            }

            foreach (var item in subtitles.Where(s => s.url.StartsWith("//")))
            {
                item.url = "https:" + item.url;
            }

            return subtitles;
        }

        return [];
    }

    // CA1054: url 保持 string —— 该方法被 BBDown 主项目直接调用（传入 Subtitle.url 字符串），
    // 改为 System.Uri 属于跨项目破坏性变更（本次改动范围仅限 BBDown.Core）
    public static async Task SaveSubtitleAsync(string url, string path, AppConfig cfg)
    {
        if (path.EndsWith(".srt"))
        {
            await File.WriteAllTextAsync(path, ConvertSubFromJson(await GetWebSourceAsync(url, cfg)), Encoding.UTF8);
        }
        else
        {
            await File.WriteAllTextAsync(path, await GetWebSourceAsync(url, cfg), Encoding.UTF8);
        }
    }

    internal static string ConvertSubFromJson(string jsonString)
    {
        StringBuilder lines = new( );
        var json = JsonDocument.Parse(jsonString);
        var sub = json.RootElement.GetProperty("body").EnumerateArray( ).ToList( );
        for (var i = 0; i < sub.Count; i++)
        {
            var line = sub[i];
            lines.AppendLine((i + 1).ToString( ));
            if (line.TryGetProperty("from", out var from))
            {
                lines.AppendLine($"{FormatTime(from.GetDouble( ))} --> {FormatTime(line.GetProperty("to").GetDouble( ))}");
            }
            else
            {
                lines.AppendLine($"{FormatTime(0.0)} --> {FormatTime(line.GetProperty("to").GetDouble( ))}");
            }
            //有的没有内容
            if (line.TryGetProperty("content", out var content))
            {
                lines.AppendLine(content.ToString( ));
            }

            lines.AppendLine( );
        }

        return lines.ToString( );
    }

    private static string FormatTime(double sec) //64.13
    {
        return TimeSpan.FromSeconds(sec).ToString(@"hh\:mm\:ss\,fff");
    }

    [GeneratedRegex("-[a-z]")]
    private static partial Regex NonCapsRegex( );
}
