<Project>

    <PropertyGroup>
        <TargetFramework>net9.0</TargetFramework>
        <LangVersion>latest</LangVersion>
        <Nullable>enable</Nullable>
        <Version>2.0</Version>
    </PropertyGroup>

    <PropertyGroup>
        <AnalysisLevel>latest-all</AnalysisLevel>
        <WarningLevel>8</WarningLevel>
        <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
        <TreatWarningsAsErrors>true</TreatWarningsAsErrors>
        <DebugType>portable</DebugType>
    </PropertyGroup>

</Project>
