<Project Sdk="Microsoft.NET.Sdk.Web">
    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <StartupObject></StartupObject>
    </PropertyGroup>
    <PropertyGroup>
        <PackageLicenseExpression>MIT</PackageLicenseExpression>
        <Description>BBDown是一个免费且便捷高效的哔哩哔哩下载/解析软件.</Description>
        <PackageProjectUrl>https://github.com/nilaoda/BBDown</PackageProjectUrl>
        <PackAsTool>true</PackAsTool>
        <ToolCommandName>BBDown</ToolCommandName>
        <PackageOutputPath>./nupkg</PackageOutputPath>
    </PropertyGroup>
    <ItemGroup>
        <PackageReference Include="QRCoder" />
        <PackageReference Include="System.CommandLine" />
    </ItemGroup>
    <ItemGroup>
        <ProjectReference Include="..\BBDown.Core\BBDown.Core.csproj" />
    </ItemGroup>
    <ItemGroup>
        <InternalsVisibleTo Include="BBDown.Tests" />
    </ItemGroup>
</Project>
