<Project>

    <!-- MSBuild 向上查找到第一个 Directory.Build.props 就停止，必须显式接力根文件 -->
    <Import Project="$([MSBuild]::GetPathOfFileAbove('Directory.Build.props', '$(MSBuildThisFileDirectory)../'))" />

    <PropertyGroup>
        <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
        <PublishAot>true</PublishAot>
        <EventSourceSupport>false</EventSourceSupport>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <InvariantGlobalization>true</InvariantGlobalization>
        <StripSymbols>true</StripSymbols>
        <ObjCopyName Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">aarch64-linux-gnu-objcopy</ObjCopyName>
    </PropertyGroup>

</Project>
