<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <OutputType>Exe</OutputType>
        <RootNamespace>BBDown.DRM</RootNamespace>
        <AssemblyName>BBDown.DRM</AssemblyName>

        <PublishAot>true</PublishAot>
        <IsAotCompatible>true</IsAotCompatible>
        <IlcOptimizationPreference>Speed</IlcOptimizationPreference>
        <IlcFoldIdenticalMethodBodies>true</IlcFoldIdenticalMethodBodies>
        <EventSourceSupport>false</EventSourceSupport>
        <UseSystemResourceKeys>true</UseSystemResourceKeys>
        <InvariantGlobalization>true</InvariantGlobalization>
        <StripSymbols>true</StripSymbols>
        <PublishTrimmed>true</PublishTrimmed>

        <!-- linux-arm64 原生 runner 未预装 GNU objcopy，AOT 剥离符号需指定（与主项目 BBDown/Directory.Build.props 一致） -->
        <ObjCopyName Condition="'$(RuntimeIdentifier)' == 'linux-arm64'">aarch64-linux-gnu-objcopy</ObjCopyName>
    </PropertyGroup>

    <ItemGroup>
        <ProjectReference Include="..\..\..\BBDown.Core\BBDown.Core.csproj" />
    </ItemGroup>

    <ItemGroup>
        <PackageReference Include="Grpc.Tools">
            <PrivateAssets>all</PrivateAssets>
            <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
        </PackageReference>
        <Protobuf Include="..\Proto\*.proto" GrpcServices="None" />
    </ItemGroup>

    <ItemGroup>
        <InternalsVisibleTo Include="BBDown.DRM.Tests" />
    </ItemGroup>

</Project>
