using BBDown.Core.Util;
using Xunit;

namespace BBDown.Core.Tests;

public class SubUtilTests
{
    [Theory]
    // 小写地区码会被规范化：zh-hans => zh-Hans
    [InlineData("zh-hans", "chi", "中文（简体）")]
    [InlineData("zh-Hans", "chi", "中文（简体）")]
    [InlineData("zh-CN", "chi", "中文（简体）")]
    [InlineData("zh-HK", "chi", "中文（香港繁體）")]
    [InlineData("zh-TW", "chi", "中文（台灣繁體）")]
    [InlineData("zh-Hant", "chi", "中文（繁體）")]
    [InlineData("ai-zh", "chi", "中文（简体, AI识别）")]
    [InlineData("ai-en", "eng", "English(generated by ai)")]
    [InlineData("en-US", "eng", "English(USA)")]
    public void GetSubtitleCode_MapsKnownLanguages(string key, string expectedCode, string expectedName)
    {
        var (code, name) = SubUtil.GetSubtitleCode(key);
        Assert.Equal(expectedCode, code);
        Assert.Equal(expectedName, name);
    }

    [Fact]
    public void ConvertSubFromJson_EmitsSequentiallyNumberedSrtBlocks()
    {
        const string json = """
        {"body":[
          {"from":0.5,"to":2.25,"content":"第一句"},
          {"from":2.25,"to":4.0,"content":"第二句"}
        ]}
        """;

        var srt = SubUtil.ConvertSubFromJson(json);

        Assert.Equal(
            "1\r\n00:00:00,500 --> 00:00:02,250\r\n第一句\r\n\r\n" +
            "2\r\n00:00:02,250 --> 00:00:04,000\r\n第二句\r\n\r\n",
            srt.ReplaceLineEndings("\r\n"));
    }

    // from 缺失时按 0 起算
    [Fact]
    public void ConvertSubFromJson_MissingFromDefaultsToZero()
    {
        var srt = SubUtil.ConvertSubFromJson("""{"body":[{"to":1.0,"content":"x"}]}""");
        Assert.Contains("00:00:00,000 --> 00:00:01,000", srt);
    }

    // content 缺失时只留空行，不应崩
    [Fact]
    public void ConvertSubFromJson_MissingContentProducesEmptyLine()
    {
        var srt = SubUtil.ConvertSubFromJson("""{"body":[{"from":0.0,"to":1.0}]}""");
        Assert.Equal("1\r\n00:00:00,000 --> 00:00:01,000\r\n\r\n", srt.ReplaceLineEndings("\r\n"));
    }

    [Fact]
    public void ConvertSubFromJson_EmptyBodyProducesEmptyString()
    {
        Assert.Equal("", SubUtil.ConvertSubFromJson("""{"body":[]}"""));
    }

    [Fact]
    public void ConvertSubFromJson_HoursAreRendered()
    {
        var srt = SubUtil.ConvertSubFromJson("""{"body":[{"from":3661.5,"to":3662.0,"content":"x"}]}""");
        Assert.Contains("01:01:01,500 --> 01:01:02,000", srt);
    }
}
