using System.Collections.Generic;
using System.Text.Json;

using BBDown.Core.Util;

namespace BBDown.Core.Tests;

public class SubUtilTests
{
    private static List<Entity.Entity.Subtitle> Read(string json, string lanKey, string urlKey, string prefix, bool intl)
    {
        using var doc = JsonDocument.Parse(json);
        return SubUtil.ReadSubtitles(doc.RootElement, lanKey, urlKey, prefix, intl);
    }

    [Fact]
    public void ReadSubtitles_MapsLanUrlAndPath( )
    {
        var subs = Read("""[{"lan":"zh-CN","subtitle_url":"//i0.hdslb.com/a.json"}]""",
            "lan", "subtitle_url", "114/114.514", false);

        var sub = Assert.Single(subs);
        Assert.Equal("zh-CN", sub.lan);
        Assert.Equal("//i0.hdslb.com/a.json", sub.url);
        Assert.Equal("114/114.514.zh-CN.srt", sub.path);
    }

    // 非国际版一律按 srt 落盘，即使 url 看着像 ass
    [Fact]
    public void ReadSubtitles_NonIntlAlwaysUsesSrtExtension( )
    {
        var subs = Read("""[{"lan":"en","subtitle_url":"https://x/a.ass"}]""", "lan", "subtitle_url", "1/1.2", false);
        Assert.Equal("1/1.2.en.srt", subs[0].path);
    }

    [Theory]
    [InlineData("https://x/a.json", "1/1.2.en.srt")]
    [InlineData("https://x/a.ass", "1/1.2.en.ass")]
    public void ReadSubtitles_IntlPicksExtensionByUrl(string url, string expectedPath)
    {
        var subs = Read($$"""[{"lang_key":"en","url":"{{url}}"}]""", "lang_key", "url", "1/1.2", true);
        Assert.Equal(expectedPath, subs[0].path);
    }

    // 国际版 app 接口返回的是转义过的斜杠
    [Fact]
    public void ReadSubtitles_UnescapesBackslashSlash( )
    {
        var subs = Read("""[{"key":"en","url":"https:\\\\/\\\\/x\\\\/a.ass"}]""", "key", "url", "1/1.2", true);
        Assert.Equal("https://x/a.ass", subs[0].url);
    }

    [Fact]
    public void ReadSubtitles_EmptyArrayProducesEmptyList( )
    {
        Assert.Empty(Read("[]", "lan", "subtitle_url", "1/1.2", false));
    }

    [Fact]
    public void ReadSubtitles_PreservesOrder( )
    {
        var subs = Read("""[{"lan":"a","subtitle_url":"1"},{"lan":"b","subtitle_url":"2"},{"lan":"c","subtitle_url":"3"}]""",
            "lan", "subtitle_url", "p", false);
        Assert.Equal(["a", "b", "c"], subs.ConvertAll(s => s.lan));
    }

    // 字段缺失直接抛，由 GetSubtitlesAsync 的候选循环判定该接口不可用
    [Fact]
    public void ReadSubtitles_ThrowsWhenFieldMissing( )
    {
        Assert.ThrowsAny<System.Exception>(( ) =>
            Read("""[{"lan":"zh-CN"}]""", "lan", "subtitle_url", "p", false));
    }

    [Theory]
    // 小写地区码会被规范化：zh-hans => zh-Hans
    [InlineData("zh-hans", "chi", "中文（简体）")]
    [InlineData("zh-Hans", "chi", "中文（简体）")]
    [InlineData("zh-CN", "chi", "中文（简体）")]
    [InlineData("zh-HK", "chi", "中文（香港繁體）")]
    [InlineData("zh-TW", "chi", "中文（台灣繁體）")]
    [InlineData("zh-Hant", "chi", "中文（繁體）")]
    [InlineData("ai-zh", "chi", "中文（简体, AI识别）")]
    [InlineData("ai-en", "eng", "English(generated by ai)")]
    [InlineData("en-US", "eng", "English(USA)")]
    [InlineData("ja", "jpn", "日本語")]
    [InlineData("ko", "kor", "한국어")]
    [InlineData("vi", "vie", "Tiếng Việt")]
    public void GetSubtitleCode_MapsKnownLanguages(string key, string expectedCode, string expectedName)
    {
        var (code, name) = SubUtil.GetSubtitleCode(key);
        Assert.Equal(expectedCode, code);
        Assert.Equal(expectedName, name);
    }

    [Theory]
    [InlineData("")]
    [InlineData("nope")]
    [InlineData("zh")]
    [InlineData("xx-YY")]
    public void GetSubtitleCode_UnknownKeyFallsBackToUndetermined(string key)
    {
        Assert.Equal(("und", "Undetermined"), SubUtil.GetSubtitleCode(key));
    }

    [Fact]
    public void ConvertSubFromJson_EmitsSequentiallyNumberedSrtBlocks( )
    {
        const string json = """
        {"body":[
          {"from":0.5,"to":2.25,"content":"第一句"},
          {"from":2.25,"to":4.0,"content":"第二句"}
        ]}
        """;

        var srt = SubUtil.ConvertSubFromJson(json);

        Assert.Equal(
            "1\r\n00:00:00,500 --> 00:00:02,250\r\n第一句\r\n\r\n" +
            "2\r\n00:00:02,250 --> 00:00:04,000\r\n第二句\r\n\r\n",
            srt.ReplaceLineEndings("\r\n"));
    }

    // from 缺失时按 0 起算
    [Fact]
    public void ConvertSubFromJson_MissingFromDefaultsToZero( )
    {
        var srt = SubUtil.ConvertSubFromJson("""{"body":[{"to":1.0,"content":"x"}]}""");
        Assert.Contains("00:00:00,000 --> 00:00:01,000", srt);
    }

    // content 缺失时只留空行，不应崩
    [Fact]
    public void ConvertSubFromJson_MissingContentProducesEmptyLine( )
    {
        var srt = SubUtil.ConvertSubFromJson("""{"body":[{"from":0.0,"to":1.0}]}""");
        Assert.Equal("1\r\n00:00:00,000 --> 00:00:01,000\r\n\r\n", srt.ReplaceLineEndings("\r\n"));
    }

    [Fact]
    public void ConvertSubFromJson_EmptyBodyProducesEmptyString( )
    {
        Assert.Equal("", SubUtil.ConvertSubFromJson("""{"body":[]}"""));
    }

    [Fact]
    public void ConvertSubFromJson_HoursAreRendered( )
    {
        var srt = SubUtil.ConvertSubFromJson("""{"body":[{"from":3661.5,"to":3662.0,"content":"x"}]}""");
        Assert.Contains("01:01:01,500 --> 01:01:02,000", srt);
    }
}
